"""init

Revision ID: f8fcaf12175a
Revises:
Create Date: 2025-11-10 09:12:47.217784

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f8fcaf12175a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
