"""initial schema

Revision ID: f92fbf4c3302
Revises: 
Create Date: 2025-11-04 15:35:22.829318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92fbf4c3302'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_url'), 'asset', ['url'], unique=True)
    op.create_table('example',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('thumbnailblurhash', sa.Text(), nullable=False),
    sa.Column('previewblurhash', sa.Text(), nullable=False),
    sa.Column('displayable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_image_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('function_name', sa.Text(), nullable=False),
    sa.Column('function_argument_string', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('zoom', sa.SmallInteger(), nullable=False),
    sa.Column('last_interacted', sa.BigInteger(), nullable=False),
    sa.Column('start_day', sa.SmallInteger(), nullable=False),
    sa.Column('end_day', sa.SmallInteger(), nullable=False),
    sa.Column('start_month', sa.SmallInteger(), nullable=False),
    sa.Column('end_month', sa.SmallInteger(), nullable=False),
    sa.Column('start_year', sa.SmallInteger(), nullable=False),
    sa.Column('end_year', sa.SmallInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('flag', sa.BigInteger(), nullable=False),
    sa.Column('vibes', sa.Text(), nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=False),
    sa.Column('count_of_room', sa.SmallInteger(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('vibe_flag', sa.BigInteger(), nullable=False),
    sa.Column('packed_date', sa.BigInteger(), nullable=False),
    sa.Column('enriched_prompt', sa.Text(), nullable=False),
    sa.Column('initial_min_price', sa.SmallInteger(), nullable=False),
    sa.Column('initial_max_price', sa.SmallInteger(), nullable=False),
    sa.Column('filter_min_price', sa.SmallInteger(), nullable=False),
    sa.Column('filter_max_price', sa.SmallInteger(), nullable=False),
    sa.Column('min_star_rating', sa.SmallInteger(), nullable=False),
    sa.Column('min_review_rating', sa.Float(), nullable=False),
    sa.Column('number_of_rooms', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('displayable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['icon_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amenity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('displayable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['icon_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_habit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('displayable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['icon_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=False),
    sa.Column('vibes', sa.Text(), nullable=False),
    sa.Column('internal_rating', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('star_rating', sa.Float(), nullable=False),
    sa.Column('main_image_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('flag', sa.BigInteger(), nullable=False),
    sa.Column('vibe_flag', sa.BigInteger(), nullable=False),
    sa.Column('comment_aggregated_rating', sa.Float(), nullable=False),
    sa.Column('number_of_rooms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_image_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_session_message',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'message_id')
    )
    op.create_table('prompt_amenity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sub_title', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('displayable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('avatar_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('compact_address', sa.Text(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('displayable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['icon_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('account_created_at', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('preferred_price_per_night', sa.SmallInteger(), nullable=False),
    sa.Column('recurrence_of_stay', sa.SmallInteger(), nullable=False),
    sa.Column('business_or_leisure', sa.SmallInteger(), nullable=False),
    sa.Column('hotel_or_villa', sa.SmallInteger(), nullable=False),
    sa.Column('token_hash', sa.BigInteger(), nullable=False),
    sa.Column('avatar_asset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('join_hotel_asset',
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['hotel_image_category.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'asset_id')
    )
    op.create_table('join_hotel_review',
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'review_id')
    )
    op.create_table('join_user_activity',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activity_id')
    )
    op.create_table('join_user_amenity',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amenity_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'amenity_id')
    )
    op.create_table('join_user_food_habit',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('food_habit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['food_habit_id'], ['food_habit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'food_habit_id')
    )
    op.create_table('join_user_session',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'session_id')
    )
    op.create_table('join_user_sport',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sport_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sport_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_user_sport')
    op.drop_table('join_user_session')
    op.drop_table('join_user_food_habit')
    op.drop_table('join_user_amenity')
    op.drop_table('join_user_activity')
    op.drop_table('join_hotel_review')
    op.drop_table('join_hotel_asset')
    op.drop_table('user')
    op.drop_table('sport')
    op.drop_table('review')
    op.drop_table('prompt_amenity')
    op.drop_table('join_session_message')
    op.drop_table('hotel')
    op.drop_table('food_habit')
    op.drop_table('amenity')
    op.drop_table('activity')
    op.drop_table('session')
    op.drop_table('message')
    op.drop_table('hotel_image_category')
    op.drop_table('example')
    op.drop_index(op.f('ix_asset_url'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
